baseurl = "/"
theme = "hello-friend"
languageCode = "en-us"
title = "BrokenSwing's blog"

enableGitInfo = true

[params]
showReadingTime = true

[languages]
[languages.en]
title = "BrokenSwing's blog"
[languages.en.params.logo]
logoText = "BrokenSwing"